# Generated by Django 4.2.3 on 2023-10-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
